---
galaxy_info:
  role_name: database
  description: MySQL, MariaDB, or PostgreSQL for Pelican Panel
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "10"

dependencies: []
