---
galaxy_info:
  role_name: pelican_app
  description: Pelican Panel application download and setup
  min_ansible_version: "2.16"
  platforms:
    - name: EL
      versions:
        - "10"

dependencies: []
